version: '3'

services:
  db:
    image: mysql:latest
    container_name: db-seguinleo-notes
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seguinleo-notes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-seguinleo-notes
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db-seguinleo-notes
      MYSQL_ROOT_PASSWORD: root

  web:
    container_name: web-seguinleo-notes
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: .
          target: /src
          ignore:
            - node_modules/
