services:
  db:
    image: mysql:latest
    container_name: db-seguinleo-notes
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seguinleo-notes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-seguinleo-notes
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db-seguinleo-notes
      MYSQL_ROOT_PASSWORD: root

  web:
    container_name: web-seguinleo-notes
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
