version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: seguinleo-notes
      MYSQL_USER: root
